### ISSUE TITLE
project_4 : unsupported pickle protocol: %d" % proto

### ISSUE THREAD

**Issue by nxnam714** [ndrplz/self-driving-car#10]
Hello,

I'm stuck in this issue when I run project 4:

$ python ./main.py 
Loading cached camera calibration... Traceback (most recent call last):
  File "./main.py", line 135, in <module>
    ret, mtx, dist, rvecs, tvecs = calibrate_camera(calib_images_dir='camera_cal')
  File "/home/nxnam/DigitalRace/hanson/self-driving-car/project_4_advanced_lane_finding/calibration_utils.py", line 20, in wrapper
    calibration = pickle.load(dump_file)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

How can I fix this?

Thank you.

**Comment by ndrplz** [comment]
Hi @nxnam714 ,

this looks a python2/3 compatibility issue. I see you're using python2. Please run the script with python3 and let me know if the issue was solved. 

I plan to put some requirements in the readme to avoid this kind of issues.
