### ISSUE TITLE
Where is the VGG pretrained model in Project 12

### ISSUE THREAD

**Issue by yangruixuan** [ndrplz/self-driving-car#2]
I got this error when I try to run the project 12

Traceback (most recent call last):
  File "main_27.py", line 284, in <module>
    run()
  File "main_27.py", line 257, in run
    image_input, keep_prob, vgg_layer3_out, vgg_layer4_out, vgg_layer7_out = load_vgg(sess, vgg_path)
  File "main_27.py", line 132, in load_vgg
    tf.saved_model.loader.load(sess, ['vgg16'], vgg_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 200, in load
    saved_model = _parse_saved_model(export_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 78, in _parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
IOError: SavedModel file does not exist at: /home/jack/code/self-driving-car/project_12_road_segmentation/data/vgg/{saved_model.pbtxt|saved_model.pb}
`

**Comment by ndrplz** [comment]
Hi @yangruixuan,

looks like you don't have the pretrained VGG model weights in the `data` directory.

You can use the `maybe_download_pretrained_vgg` function in [`helper.py`](https://github.com/ndrplz/self-driving-car/blob/master/project_12_road_segmentation/helper.py) in order to download the pretrained model.

**Comment by yangruixuan** [comment]
Hi @ndrplz Thank you for your help. I also found main_27.py is different from main.py and helper.py only can run under python3.
