### ISSUE TITLE
project_5_vehicle_detection -- Got TypeError: 'module' object is not callable when run main_ssd.py

### ISSUE THREAD

**Issue by binlidaily** [ndrplz/self-driving-car#20]
When I run main_ssd.py I got this:
```shell
Traceback (most recent call last):
  File "/home/binli/self-driving-car/project_5_vehicle_detection/main_ssd.py", line 10, in <module>
    ssd_model, bbox_helper, color_palette = get_SSD_model()
  File "/home/binli/self-driving-car/project_5_vehicle_detection/SSD.py", line 805, in get_SSD_model
    model_ssd = SSD300(input_shape=(300, 300, 3), num_classes=NUM_CLASSES, pretrained=True)
  File "/home/binli/self-driving-car/project_5_vehicle_detection/SSD.py", line 679, in SSD300
    mode='concat', concat_axis=1, name='mbox_loc')
TypeError: 'module' object is not callable
```
I tried a lot but I cannot fix this? Any suggestions about this? @ndrplz thanks a lot

**Comment by ndrplz** [comment]
Not at the pc right now, but from the stack trace it looks like an issue of the merge function.

Take a look that the one in the code is still a valid way for merging activations. The keras version is now legacy
